---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: headlamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headlamp
  template:
    metadata:
      labels:
        app: headlamp
    spec:
      serviceAccountName: headlamp
      containers:
        - name: headlamp
          image: ghcr.io/headlamp-k8s/headlamp:v0.43.0@sha256:b068ecfb496a50b837990e60391d5ffba9f3f2c0dafdb6bcdf681410eb776018
          args: ["--in-cluster", "--port=4466"]
          env:
            - name: HEADLAMP_BACKEND_TOKEN
              valueFrom:
                secretKeyRef:
                  name: headlamp-token
                  key: token
          ports:
            - containerPort: 4466
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 100
