---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhosting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhosting
  template:
    metadata:
      labels:
        app: webhosting
    spec:
      containers:
        - name: nginx
          image: nginx:1.31.2@sha256:ec4ed8b5299e5e90694af7750eb6dffd2627317d30544d056b0371f8082f7bce
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: webhosting-data
      volumes:
        - name: webhosting-data
          persistentVolumeClaim:
            claimName: webhosting-data-pvc
