---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: disk-usage-report
  namespace: downloaders
---
# minimal RBAC the workflow executor needs to act as a workflow executor
# https://argo-workflows.readthedocs.io/en/latest/workflow-rbac/
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-executor
  namespace: downloaders
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflowtaskresults
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-executor
  namespace: downloaders
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow-executor
subjects:
  - kind: ServiceAccount
    name: disk-usage-report
    namespace: downloaders
