---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ai-readonly
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ai-readonly
subjects:
  - kind: ServiceAccount
    name: ai-readonly
    namespace: ai-readonly
