apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo
resources:
  - ../../base/argo-workflows
  - ingress.yaml
patches:
  - target:
      kind: Deployment
      name: argo-server
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --secure=false
      - op: replace
        path: /spec/template/spec/containers/0/readinessProbe/httpGet/scheme
        value: HTTP
