apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:PYqkFYEPxea3ihKT7bDZlbwGs+Pqz+NfvvcyxywotEr7RminvIX6MaknVhAtn564RFCmbxm1FTT4kE2BuZGp26ulKx1O6w8C6wMuNe7P92avZdRJsKaRa/4egZfnlX7x5o6peFBGo6xhf4gMgSWyrsQeIxaZXJrMS5KlnTVSLBZOFGwGxBQPeHuQOF6nKsapmETQiDDCyh55fRbwok3xdoEKdzn6C8q4U2KNlbZLvK2Lp6Tw8eO1Pd/TVeaPL4jUBh9UU0F8kicRMO1xgYM1iVdEkIPwXqgWzW7ZxmMgIAkZkeXisDuwU6XHK80=,iv:USLtTd8XwQTUOQk0hDQ9skBXGSrVHZ1b3mApcc1HhVo=,tag:e5Bzw+MEY8fLWwYMSR3Ssw==,type:str]
kind: Secret
metadata:
    name: headlamp-tunnel-credentials
    namespace: headlamp
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN3IydThBblEraUVaOTk3
            MGNBem56Smd2NTV5Vlp3L1hnYXJ1TFVmOVNZCkdPeUUvUTJqNW9ZeXowOWl4YUlr
            WXFyZ3NLQ2tmODNrMExwWGdkVS8wTWMKLS0tIHAwQVRzVFozaXh0NEVFaDVBWWJU
            bEdNQkNsdmgvVXJodUo4WGxqVEZQT1UKCXMRuqH+1SEK5pvUIfmo9sPDdaNi+i0o
            g17a72FjfRrqC1UzDo7DJ/qLpsyiU+FmJ1jhhitzhZE2IyghMEgxCw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jnfhet7cj900tg9f0dwgqktjwux4km4hen8gnevpujm5260sayesujm92y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T12:28:38Z"
    mac: ENC[AES256_GCM,data:+hW405hQhM3FDZA0LFUreulw7wffIEi0yD4caelAFEoSdjeB8KNBzt+UPywzKnaJ6By34OWLgsDlSxnzLX4KAn+cQTK6UkwqkHUxNzvaFqrZ9moZ5rrPIFqUUjGsL1kkPgzAlZ3iF4HOTCG4rkhQHyJfknVF9viv8N2w+yJyNRY=,iv:TAN8kEMZdNMGHQFIxLrPCxDlKA6tT/dMFCjoJ2nqKPI=,tag:JM89AETtG+b+6iqAD4h7PQ==,type:str]
    version: 3.13.1
