---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-study-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: devops-study-app
  template:
    metadata:
      labels:
        app: devops-study-app
    spec:
      containers:
        - image: ghcr.io/milanoid-labs/study-app-api:backend-v0.2.7@sha256:5df0c97f378b48f730500236572e7225486f864182f246d41217dbdebf46f437
          name: devops-study-app-backend
          ports:
            - containerPort: 22112
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
