---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-study-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: devops-study-app
  template:
    metadata:
      labels:
        app: devops-study-app
    spec:
      containers:
        - image: ghcr.io/milanoid-labs/study-app-api:backend-v0.2.11@sha256:48eb1b5a540e5b080c2601f4bf2cbd3e43e945f6bda62e14e6221a537c03bc6f
          name: devops-study-app-backend
          ports:
            - containerPort: 22112
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
