apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-telegram
    namespace: monitoring
type: Opaque
stringData:
    bot-token: ENC[AES256_GCM,data:nuDtGkAk9d4sHe/gK1Aog/3DMj3Rv4K2QhJFfD2EjzeU3D/ydPlpHrWirupUSg==,iv:hmzBv0GjguDtYN6A//0hKnSSMJTXHbFcVDS6Uw/0wKY=,tag:uUTxrkITY0luakFNFT+b2Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUzRaTU5ZQ3VtZExVd0dr
            WWZINjQ0VVgzKzlWZjF1MkRqMkM1YnBGWmpFCk53Q2hBdXFNVVpXNDZFeUJrOXVM
            bVQzQ2dxWUhuUnVyREpjT1o4OHlaTjgKLS0tIE9nZjZWTGxYS2Z6VHk0bmxUcTh2
            WnVIbFdsRFpMb1lKR3JoemJoOWlvMlkKS2qy+gZHR2jwmzUyG8Rw9TFnXos3ckyr
            zMJ2CLYCbX6gXBHmjSL2JoOwPI3HRytGtkPEiC6U37HAAisrieCFpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jnfhet7cj900tg9f0dwgqktjwux4km4hen8gnevpujm5260sayesujm92y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T06:51:03Z"
    mac: ENC[AES256_GCM,data:JQuZvl1bcNRvtXiaRW9lTw4j4aMnVgRjc61y58cELB0mPhgB2qPToDjp1IM/6vjWXJptSWewVGf06ENiNXLasgIR6/5VHK0hZVhdeH0BOzc37XDRpoTLA1q+stSk4rE2E3ph0wOs9uz965p6Q3CQF0G585i6Dxh1zkDjPxaiCwg=,iv:gOigeNo0M9uBhPLeTheLbAUQ2NZnCSJlKytZZEisDio=,tag:AIz4+GdFOOasNBZ3AtmetA==,type:str]
    version: 3.13.3
