---
name: Run job in a container

on:
  workflow_dispatch:
    inputs:
      sleep_seconds:
        description: how long the workflow shoudl sleep? (s)
        default: '300'
        type: string

jobs:
  hello:
    runs-on: homelab-runners
    container:
      image: node:24@sha256:22f6fe5f59fb7fed238b19623506d573dffaa932ce33b84ce541a9a2e0eade28
      env:
        NODE_ENV: development
    steps:
      - name: Hello from homelab
        run: |
          echo "Hello from self-hosted runner on $(hostname)"
          echo "sleeping for ${{inputs.sleep_seconds}} seconds"
          sleep ${{inputs.sleep_seconds}}
