---
name: Run job in a container

on:
  workflow_dispatch:
    inputs:
      sleep_seconds:
        description: how long the workflow shoudl sleep? (s)
        default: '300'
        type: string

jobs:
  hello:
    runs-on: homelab-runners
    container:
      image: node:24@sha256:3d27e5c11e5786e309ec3e03f93ae536eb36e6e5eb3714d5eb3300a36157add0
      env:
        NODE_ENV: development
    steps:
      - name: Hello from homelab
        run: |
          echo "Hello from self-hosted runner on $(hostname)"
          echo "sleeping for ${{inputs.sleep_seconds}} seconds"
          sleep ${{inputs.sleep_seconds}}
