---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "0 6 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - name: mint-token
              image: alpine:3.24@sha256:5b02b42e375f7426f8d65c3af331ca05d9878f9989230354504e0b9dfd431f60
              command: ["/bin/sh", "/scripts/mint-token.sh"]
              env:
                - name: GITHUB_APP_ID
                  valueFrom:
                    configMapKeyRef:
                      name: renovate-configmap
                      key: GITHUB_APP_ID
                - name: GITHUB_INSTALLATION_ID
                  valueFrom:
                    configMapKeyRef:
                      name: renovate-configmap
                      key: GITHUB_INSTALLATION_ID
                - name: GITHUB_APP_KEY
                  valueFrom:
                    secretKeyRef:
                      name: renovate-container-env
                      key: GITHUB_APP_KEY
              volumeMounts:
                - name: shared
                  mountPath: /shared
                - name: mint-script
                  mountPath: /scripts
              securityContext:
                allowPrivilegeEscalation: false

          containers:
            - name: renovate
              image: renovate/renovate:43.288.0@sha256:3b72fc4274c56f65f53dcd4dcbed3143289358e0a2d96f7af215e6cf1923e5f6
              command: ["/bin/sh", "-c"]
              args:
                - export RENOVATE_TOKEN=$(cat /shared/token) && renovate milanoid-labs/homelab-cluster milanoid-labs/devops-study-app milanoid-labs/home-dashboard

              envFrom:
                - configMapRef:
                    name: renovate-configmap
              env:
                - name: RENOVATE_HOST_RULES
                  valueFrom:
                    secretKeyRef:
                      name: renovate-nexus-env
                      key: RENOVATE_HOST_RULES
              volumeMounts:
                - name: shared
                  mountPath: /shared
                  readOnly: true
              resources:
                requests:
                  cpu: 100m
                  memory: 512Mi
                limits:
                  cpu: "1"
                  memory: 1Gi

          volumes:
            - name: shared
              emptyDir: {}
            - name: mint-script
              configMap:
                name: renovate-mint-token-script
                defaultMode: 0755

          restartPolicy: Never
