apiVersion: v1
kind: Secret
metadata:
    name: renovate-nexus-env
    namespace: renovate
stringData:
    RENOVATE_HOST_RULES: ENC[AES256_GCM,data:tqsmJmdvsrkIo+5/RjKmRq4RRvccCzARYvyijVPvzzpuAxYuIrIctnOUc0ZiX+Q6losoNMiHRMyp5nS7CGkSmTzNEBAc1/BOjhiVbFLvlYMv3Ut5jBBwuhvXk+j5OnZFXIL2quXTgY5h8C+X/rzBHniLIZXJcKCZ,iv:JA7YWP46xeCqYTv4hxY3nONL5vP0V8qLIvQwSGDNLgc=,tag:QLfVutobrdZftygeJm9oKg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWkhJSCtlamdGU1VBUWhx
            SzdLTkN6cFIxWjkxU3NVM1liZnN2NzlMZG1rCkc3L2JuRW5lM0ljYmtRbm5PRDV6
            L0d3M2FzRk55VVFIZ3IwTW9ta00yeFEKLS0tICs5UFdJZEdpR0ZWc2lRemt0RkNC
            OWliVFE2TjFtQ2FveUJMcDlLTEROYnMKWr/WvRrIA8N0YgNLaZquS0bMjoebqwPU
            UzOqhIFxm17kmPgsw/yg8FkGa85egJDQlgK4mexXHYsbpL3u68IxWw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jnfhet7cj900tg9f0dwgqktjwux4km4hen8gnevpujm5260sayesujm92y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T17:26:42Z"
    mac: ENC[AES256_GCM,data:qL472hMTY1P+uJnQcrlpLJ83rloMk43WeFGF+TDAdcatiXgdSCUmUb5cJKAiBZoEWOWD+J2EqxpC70BD7wjY4HFKOl76a0vUdaS/F/UAhgnxK+Yqj1KTiTdkqwgDaHS8JZ2jPenHTB/gzCDVXf5j/pLxdHGrhplst/WCxkYRo2E=,iv:W/1FPTQjjPziaOpLsV5ChtQ8lbweQgvOfHIB0y0DUFo=,tag:zjh5uutOng1MbO9oMCpm9A==,type:str]
    version: 3.13.1
